default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: login_google_development

test:
  <<: *default
  database: login_google_test

#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: login_google_production
  username: login_google
  password: <%= ENV['LOGIN_GOOGLE_DATABASE_PASSWORD'] %>
